In [1]:
import gurobipy as grb
from gurobipy import GRB
import scipy.sparse as spr
import numpy as np
import random
import matplotlib.pyplot as plt
#from sympy import symbols, Rational
from IPython.display import display, Math, Markdown
import numpy.ma as ma
import scipy as sp

In [2]:
class OneToOneITU():
    def __init__(self, n, m, parameters , lbs=(0, 0), tol=1e-9):
        self.n = n
        self.m = m
        self.lb_U, self.lb_V = lbs
        self.tol = tol 
       
        self.A_ij = parameters[0]
        self.B_ij = parameters[1]

    def D_ij(self, U_i, V_j):
        return (U_i[:, None] + self.A_ij * V_j[None, :] - self.B_ij)/(1+ self.A_ij)

    def get_U_ij(self, V_j, i_idx ,j_idx = None):
        if j_idx is None:
            return self.B_ij[i_idx] - self.A_ij[i_idx] * V_j[None, :]
        else:
            return self.B_ij[i_idx,j_idx] - self.A_ij[i_idx,j_idx] * V_j[None, j_idx]

    def get_V_ij(self,i_idx, j_idx , U_i):
        return (self.B_ij[i_idx,j_idx] -  U_i)/ self.A_ij[i_idx,j_idx]

In [3]:
def transpose_mkt(self):
    n, m = self.n, self.m
    self.m = n
    self.n = m

    self.A_ij = 1 / self.A_ij.T
    self.B_ij = self.B_ij.T/ self.A_ij

OneToOneITU.transpose_mkt = transpose_mkt

In [4]:
def ITU_parallel_auction(self):

    V_j = np.ones(self.m) * self.lb_V
    mu_ij = np.ones( self.n, dtype= int) * (self.m +1)

    unassigned = np.where(mu_ij == self.m + 1)[0] 
    n_unassigned = len(unassigned)
    iter = 0

    while n_unassigned > 0:# and iter <500000:
        U_ij = self.get_U_ij( V_j, unassigned)
        # print(U_ij)
        perm_unmatched = np.all(U_ij <= self.lb_U, axis = 1)
        
        if np.any(perm_unmatched):
            mu_ij[unassigned] += (self.m - mu_ij[unassigned]) * perm_unmatched
            # print(perm_unmatched)
            # print(mu_ij)
        
        else:
            
            U_ij = np.concatenate((U_ij, self.lb_U * np.ones((n_unassigned,1))), axis = 1)
            U_ij_sorted_id = np.argsort(U_ij, axis = 1)
            j_i = U_ij_sorted_id[:,-1]
            w_i = U_ij[np.arange(n_unassigned),U_ij_sorted_id[:,-2] ]
      
            j_unique = np.unique(j_i)
            #offers = w_i[:,None] * ( j_i[:,None] == j_unique[None,:])  - 1e22 *  ( j_i[:,None] != j_unique[None,:]) 
            #print(np.shape( self.get_V_ij(unassigned[:,None],j_unique[None,:],w_i[:,None])))
            offers = (self.get_V_ij(unassigned[:,None],j_unique[None,:],w_i[:,None]) * ( j_i[:,None] == j_unique[None,:]) 
                       - 1e22 *  ( j_i[:,None] != j_unique[None,:]) )
            i_j_among_unass = np.argmax(offers, axis = 0)
            i_j = unassigned[ i_j_among_unass]
            best_offer_j = np.max(offers, axis = 0)

            # print(i_j)
            #print(offers.round(1))
            

            mu_ij[  np.any( mu_ij[:,None] == j_unique , axis = 1) ] = self.m +1
            mu_ij[i_j] = j_unique
            # print(mu_ij)
            

            #V_j[j_unique] += np.maximum(self.get_V_ij(i_j,j_unique, best_offer_j) - V_j[j_unique], self.tol)
            V_j[j_unique] += np.maximum(best_offer_j - V_j[j_unique], self.tol)
            
        unassigned = np.where(mu_ij == self.m + 1)[0]
        # print(unassigned)
        n_unassigned = len(unassigned)
        iter += 1


    matched_i =  mu_ij < self.m
    U_i = np.ones(self.n) * self.lb_U
    U_i[matched_i] = self.get_U_ij(V_j, matched_i)[np.arange(matched_i.sum()), mu_ij[matched_i]]
    mu_ij = mu_ij[:,None] == np.arange(self.m +1)
    
    

    return mu_ij, U_i, V_j


OneToOneITU.ITU_parallel_auction = ITU_parallel_auction

#### Generate a parametrized example

In [5]:
np.random.seed(10)
n_i = 350
m_j = 400

θ_true =  np.array([1,-1,1,-1])
k = len(θ_true)
X_ijk = np.random.normal(1,1, size = [n_i,m_j, k])
 

A = np.exp( X_ijk[:,:,:2] @ θ_true[:2])
B = X_ijk[:,:,2:4] @ θ_true[2:4]

In [6]:
obs_mrk = OneToOneITU( n_i,m_j, (A,B), tol=0.00001)

In [7]:
mu_obs, u_true, v_true= obs_mrk.ITU_parallel_auction()

In [8]:
np.min((u_true[:,None] + obs_mrk.A_ij * v_true[None,:] - obs_mrk.B_ij) / (1+obs_mrk.A_ij))

0.0

In [9]:
np.min(obs_mrk.D_ij(u_true, v_true) )

0.0

In [10]:
print( np.max(mu_obs[:,-1] * ( u_true - obs_mrk.lb_U)))
print( np.max((mu_obs[:,:-1].sum(0) == 0) * ( v_true - obs_mrk.lb_V)))

0.0
0.0


In [11]:
print(np.all(mu_obs[:,:-1].sum(0) <= 1))
print(np.all(mu_obs[:,:-1].sum(1) <= 1))

True
True


####  Now let us compute the $j$-favourite solution.

In [12]:
# obs_mrk.transpose_mkt()
# mu_obs_i_fav, v_true_i_fav, u_true_i_fav= obs_mrk.ITU_parallel_auction()
# print(np.min(obs_mrk.D_ij(v_true_i_fav, u_true_i_fav) ))
# print( np.max(mu_obs_i_fav[:,-1] * ( v_true_i_fav - obs_mrk.lb_U)))
# print( np.max((mu_obs_i_fav[:,:-1].sum(0) == 0) * ( u_true_i_fav - obs_mrk.lb_V)))
# obs_mrk.transpose_mkt()

In [13]:
# obs_mrk.get_U_ij(u_true_i_fav, np.arange(obs_mrk.n)).round(2)

In [14]:
# v_true_i_fav

In [15]:
# u_true_i_fav

In [16]:
# u_true


In [17]:
# mu_obs_i_fav *1

In [18]:
# obs_mrk.get_V_ij(True, True,v_true_i_fav[:,None]).round(0)

In [19]:
# obs_mrk.D_ij(v_true_i_fav, u_true_i_fav) 

In [20]:
# mu_obs[:,:-1]*1

In [21]:
# mu_obs_i_fav[:,:-1].T *1

In [22]:
# obs_mrk.get_U_ij(v_true_i_fav, np.arange(obs_mrk.n))

In [23]:
# np.min(u_true_i_fav - u_true)

# Estimation

In [24]:
def Q(self,θ,mu_obs,X_ijk):
    A_θ = np.exp( X_ijk[:,:,:2] @ θ[:2])
    B_θ = X_ijk[:,:,2:4]  @ θ[2:4]

    mkt_θ = OneToOneITU( n_i,m_j, (A_θ,B_θ), tol= .0001)
    mu_θ, u_θ, v_θ = mkt_θ.ITU_parallel_auction()


    Q_θ = ( (mu_obs[:,:-1] * mkt_θ.D_ij(u_θ, v_θ) ).sum() + 
            (mu_obs[:,-1] * u_θ ).sum() + 
            ((mu_obs[:,:-1].sum(0) == 0) * v_θ).sum() +
            np.log( mu_θ.sum()) +
            ((v_true - v_θ)**2).sum())
    


    print(Q_θ)
    print( θ.round(3))
    return Q_θ

OneToOneITU.Q = Q

In [25]:
obs_mrk.Q(np.array([-1,.5,2,-1]), mu_obs, X_ijk)

11591.905100384973
[-1.   0.5  2.  -1. ]


11591.905100384973

In [26]:
def maximum_score_estimator(self,θ_0,mu_obs,X_ijk ):

    problem = sp.optimize.minimize( lambda θ: self.Q(θ,mu_obs,X_ijk)  ,θ_0)  

    return problem.x


OneToOneITU.maximum_score_estimator = maximum_score_estimator

In [27]:
obs_mrk.maximum_score_estimator( np.array([0,0,0,0]), mu_obs,X_ijk )

6418.355322240411
[0. 0. 0. 0.]
6418.355322240411
[0. 0. 0. 0.]
6418.355322240411
[0. 0. 0. 0.]
6418.251320755981
[0. 0. 0. 0.]
6418.24649569943
[0. 0. 0. 0.]
6584.386596998937
[0.    0.    0.698 0.73 ]


6584.386598190523
[0.    0.    0.698 0.73 ]
6584.386595989517
[0.    0.    0.698 0.73 ]
6584.38660127462
[0.    0.    0.698 0.73 ]
6584.3865980124265
[0.    0.    0.698 0.73 ]
6455.06315251931
[0.    0.    0.233 0.243]
6455.063153549248
[0.    0.    0.233 0.243]
6455.063152676314
[0.    0.    0.233 0.243]
6455.063155763513
[0.    0.    0.233 0.243]
6455.063152236764
[0.    0.    0.233 0.243]
6428.5203253272375
[0.    0.    0.078 0.081]
6428.520325702374
[0.    0.    0.078 0.081]
6428.520325472801
[0.    0.    0.078 0.081]
6428.520328378774
[0.    0.    0.078 0.081]
6428.5203244683435
[0.    0.    0.078 0.081]
6421.508678832571
[0.    0.    0.026 0.027]
6421.508678963675
[0.    0.    0.026 0.027]
6421.508678886313
[0.    0.    0.026 0.027]
6421.508674016845
[0.    0.    0.026 0.027]
6421.508685241625
[0.    0.    0.026 0.027]
6419.377296153223
[0.    0.    0.009 0.009]
6419.377296196826
[0.    0.    0.009 0.009]
6419.377296168827
[0.    0.    0.009 0.009]
6419.377291966308
[0.    0.    

array([ 0.97379571, -0.98960075,  1.04197269, -0.99559837])